--- #YAML:1.0
name:                DBIx-Log4perl
version:             0.11
abstract:            Perl extension for DBI to selectively log SQL,
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    DBI:                           1.5
    Log::Log4perl:                 1.04
    Test::More:                    0.62
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Martin J. Evans <mjevans@cpan.org>
